export const bairros = [
    "ÁGUA BRANCA", "ALTO DA BALANÇA", "ALTO DO CIGANO", "ALTO JOSÉ LEAL", "ALTO JOSÉ LEITE",
    "ALTO NOSSA SENHORA DO AMPARO", "ALVINHO", "BAIRRO NOBRE", "BAIRRO NOVO", "BELA VISTA",
    "BELA VISTA II", "BIDA", "BORGES", "CAIC", "CAIÇARA I", "CAIÇARA II", "CAIÇARA III", 
    "CAJÁ", "CAJUEIRO", "CAMPINAS", "CENTRO", "CIDADE DE DEUS", "COLINAS DO CANADÁ", 
    "COLORADO", "CUSCUZ", "DOIS TERREIROS", "ESPÍRITO SANTO", "FERREIROS", "GALILEIA", 
    "IRÃ", "JARDIM IPIRANGA", "JARDIM SÃO PEDRO", "LADEIRA DE PEDRA", "LAGOA REDONDA I", 
    "LAGOA REDONDA II", "LÍDIA QUEIROZ", "LIVRAMENTO", "LOTEAMENTO AZOUBEL", 
    "LOTEAMENTO ALTO DA VITÓRIA", "LOTEAMENTO BELO HORIZONTE", "LOTEAMENTO CONCEIÇÃO I", 
    "LOTEAMENTO CONCEIÇÃO II", "LOTEAMENTO DE BAU", "LOTEAMENTO GALILÉIA", 
    "LOTEAMENTO JOSÉ DE LEMOS", "LOTEAMENTO MAJOR EXPEDITO", "LOTEAMENTO PARAÍSO", 
    "LOTEAMENTO PORTAL DO SOL", "LOTEAMENTO REAL", "LOTEAMENTO SÃO SEVERINO", 
    "LOTEAMENTO TROPICAL", "LOTEAMENTO VENEZA", "LOTEAMENTO VISTA BELA", "LUIZ GONZAGA", 
    "MALVINA", "MANGUEIRA", "MAUÉS", "MARANHÃO", "MÁRIO BEZERRA", "MATADOURO", "MATRIZ", 
    "MILITINA", "OITEIRO", "NATUBA", "PAU SANTO", "PACAS", "PINGA FOGO", "PIRITUBA", 
    "PRESIDENTE KENEDY", "REDENÇÃO", "SANTANA", "SANTO ANTÃO", "SANTO IVO", 
    "MAUES - SÃO VICENTE DE PAULO", "SERRA GRANDE", "SÍTIO DO MEIO", "TREZE", 
    "UNIVERSITÁRIO", "VILA UNIÃO", "ZONA RURAL"
].sort();

export const estados = [
    { sigla: "AC", nome: "Acre" },
    { sigla: "AL", nome: "Alagoas" },
    { sigla: "AP", nome: "Amapá" },
    { sigla: "AM", nome: "Amazonas" },
    { sigla: "BA", nome: "Bahia" },
    { sigla: "CE", nome: "Ceará" },
    { sigla: "DF", nome: "Distrito Federal" },
    { sigla: "ES", nome: "Espírito Santo" },
    { sigla: "GO", nome: "Goiás" },
    { sigla: "MA", nome: "Maranhão" },
    { sigla: "MT", nome: "Mato Grosso" },
    { sigla: "MS", nome: "Mato Grosso do Sul" },
    { sigla: "MG", nome: "Minas Gerais" },
    { sigla: "PA", nome: "Pará" },
    { sigla: "PB", nome: "Paraíba" },
    { sigla: "PR", nome: "Paraná" },
    { sigla: "PE", nome: "Pernambuco" },
    { sigla: "PI", nome: "Piauí" },
    { sigla: "RJ", nome: "Rio de Janeiro" },
    { sigla: "RN", nome: "Rio Grande do Norte" },
    { sigla: "RS", nome: "Rio Grande do Sul" },
    { sigla: "RO", nome: "Rondônia" },
    { sigla: "RR", nome: "Roraima" },
    { sigla: "SC", nome: "Santa Catarina" },
    { sigla: "SP", nome: "São Paulo" },
    { sigla: "SE", nome: "Sergipe" },
    { sigla: "TO", nome: "Tocantins" }
  ].sort();

  export const ubs = [
    "USF CIDADE DE DEUS",
    "USF MATADOURO",
    "USF REDENÇÃO",
    "USF REDENÇÃO 2",
    "USF LÍDIA QUEIROZ",
    "USF LÍDIA QUEIROZ 2",
    "USF ÁGUAS BRANCAS",
    "USF ÁGUA BRANCA 2",
    "USF CAIC",
    "USF LOTEAMENTO CONCEIÇÃO I",
    "USF LOTEAMENTO CONCEIÇÃO II",
    "ANEXO IRÃ",
    "USF MILITINA",
    "EAP MILITINA 1",
    "USF SANTANA",
    "EAP SANTANA 2",
    "USF AMPARO",
    "EAP AMPARO 2",
    "USF JARDIM IPIRANGA",
    "USF JARDIM IPIRANGA 2",
    "USF JARDIM IPIRANGA II",
    "USF LIVRAMENTO",
    "USF LIVRAMENTO II",
    "USF LIVRAMENTO III",
    "USF MÁRIO BEZERRA",
    "USF MÁRIO BEZERRA II",
    "USF MARANHÃO",
    "EAP ANEXO MARANHÃO",
    "USF DR. ALVINHO",
    "USF MATRIZ",
    "USF MATRIZ ANEXO PRIMITIVO",
    "USF ALTO JOSÉ LEAL",
    "USF ALTO JOSÉ LEAL 2",
    "EAP ALTO JOSÉ LEAL 3",
    "USF BELA VISTA 1",
    "USF BELA VISTA II",
    "USF BELA VISTA III",
    "ANEXO ALTO DO RESERVATÓRIO",
    "USF LOTEAMENTO DE BAU",
    "USF CAIÇARA",
    "USF CAIÇARA III",
    "USF LUIZ GONZAGA",
    "USF CAJUEIRO",
    "USF MAUÉS",
    "USF MAUÉS II",
    "USF LAGOA REDONDA",
    "USF OITEIRO",
    "USF OITEIRO SAUDE ATE + TARDE",
    "USF PACAS",
    "USF SERRA GRANDE",
    "USF GALILEIA",
    "USF NATUBA",
    "USF PIRITUBA I",
    "USF PIRITUBA II",
    "USF PIRITUBA III",
    "EAP LADEIRA DE PEDRAS 1 (OITI)",
    "USF LADEIRA DE PEDRAS",
    "USF GAMILEIRA",
    "USF PAU SANTO",
    "OUTRAS",
  ].sort();

  export const especializada = [
    "CEO I - CENTRO DE ESPECIALIDADES ODONTOLÓGICAS 1 ", "CEO II - CENTRO DE ESPECIALIDADES ODONTOLÓGICAS 2",
    "CEAMI", "CEAMI +", "NASM", "POLICLÍNICA DA CRIANÇA", "UPAE", "CTA", "SAMU",
    "SERVIÇO DE ATENDIMENTO DOMICILIAR (SAD)", "CENTRO DE ATENÇÃO PSICOSSOCIAL (CAPS)",
    "CLÍNICA MUNICIPAL DO CORAÇÃO", "CLÍNICA DE FISIOTERAPIA - CRER", "SEDE", "CLÍNICA DA MULHER", "CLÍNICA DE OLHOS",
    "FARMÁCIA PARCEIRA","OUTRAS",

  ].sort();

 export const setoresAdministrativos = [

    // Setores Administrativos
  "Diretoria Administrativa","Setor de Recursos Humanos","Financeiro e Contabilidade","Compras e Suprimentos",
  "Tecnologia da Informação",  "Ouvidoria",  "Assessoria Jurídica",  "Planejamento e Gestão",  "Almoxarifado",
  "Patrimônio",  "Comunicação e Marketing",  "Atendimento ao Paciente",  "Gestão de Projetos",  "Serviço Social",
  "Gestão de Contratos",  "Transporte e Logística",  "Manutenção",  "Recepção",
].sort();

export const setoresEspecializados = [    // Setores de Unidades de Saúde Especializadas
  "Pronto Atendimento",  "Centro Cirúrgico",  "Centro Obstétrico",  "Pediatria",
  "Oncologia",  "Cardiologia",  "Neurologia",  "Ortopedia",  "Psiquiatria",
  "Endocrinologia",  "Dermatologia",  "Nefrologia",  "Oftalmologia",
  "Otorrinolaringologia",  "Geriatria",  "Fisioterapia",  "Radiologia",
  "Laboratório de Análises Clínicas",  "Centro de Reabilitação",  "Vigilância Ambiental",
  "Vigilância Epidemiológica",  "Vigilância Sanitária",  "Centro de Especialidades Médicas",
  "Centro de Abastecimento Farmaceutico - CAF",  "Transporte Fora de Domicílio - TFD",
  "Regulação em saúde", "Consultório Médico","Consultório Odontológico","Consultório Enfermagem",
  "Sala de Vacina","Consultório Médico", "Outros"

  
].sort();

export const opcoesEstadoConservacao = [
  { value: "NOVO", label: "NOVO (Sem uso, em perfeito estado)" },
  { value: "ÓTIMO", label: "ÓTIMO (Usado, mas como novo)" },
  { value: "BOM", label: "BOM (Pequenos sinais de uso, funcionando bem)" },
  { value: "REGULAR", label: "REGULAR (Funcionando, mas com desgastes visíveis)" },
  { value: "RUIM", label: "RUIM (Funcionando parcialmente ou com falhas)" },
  { value: "OCIOSO", label: "OCIOSO (Sem uso, mas em condições de uso)" },
  { value: "OCUPADO", label: "OCUPADO (Em uso atualmente)" },
  { value: "INSERVÍVEL", label: "INSERVÍVEL (Quebrado ou inutilizável)" },
  { value: "EM MANUTENÇÃO", label: "EM MANUTENÇÃO (Atualmente em reparo)" },
  { value: "DESCARTADO", label: "DESCARTADO (Desativado e separado para descarte)" },
];

export const TextosInstitucionais = {
  descricao: "O VISAVSA é um sistema moderno, seguro e inteligente desenvolvido para otimizar a gestão",
  adm:"Disponível 24 horas por dia, a plataforma permite o controle ."
};

export const OpcoesSelect = {
  sexo: [
    { value: "", label: "Selecione" },
    { value: "M", label: "Masculino" },
    { value: "F", label: "Feminino" },
    { value: "O", label: "Outro" },
    { value: "N", label: "Prefiro não informar" }
  ],
  
  racaCor: [
    { value: "", label: "Selecione" },
    { value: "Branca", label: "Branca" },
    { value: "Preta", label: "Preta" },
    { value: "Parda", label: "Parda" },
    { value: "Amarela", label: "Amarela" },
    { value: "Indígena", label: "Indígena" },
    { value: "Não declarado", label: "Não declarado" }
  ],
  
  estadoCivil: [
    { value: "", label: "Selecione" },
    { value: "Solteiro(a)", label: "Solteiro(a)" },
    { value: "Casado(a)", label: "Casado(a)" },
    { value: "Divorciado(a)", label: "Divorciado(a)" },
    { value: "Viúvo(a)", label: "Viúvo(a)" },
    { value: "Separado(a)", label: "Separado(a) judicialmente" },
    { value: "União Estável", label: "União Estável" }
  ],
  
  escolaridade: [
    { value: "", label: "Selecione" },
    { value: "Analfabeto", label: "Analfabeto" },
    { value: "Até 5º ano incompleto", label: "Até 5º ano incompleto" },
    { value: "5º ano completo", label: "5º ano completo" },
    { value: "6º ao 9º ano incompleto", label: "6º ao 9º ano incompleto" },
    { value: "Fundamental completo", label: "Fundamental completo" },
    { value: "Médio incompleto", label: "Médio incompleto" },
    { value: "Médio completo", label: "Médio completo" },
    { value: "Superior incompleto", label: "Superior incompleto" },
    { value: "Superior completo", label: "Superior completo" },
    { value: "Pós-graduação", label: "Pós-graduação" },
    { value: "Mestrado", label: "Mestrado" },
    { value: "Doutorado", label: "Doutorado" }
  ],

  uf: [
    { value: "", label: "Selecione" },
    { value: "AC", label: "AC" },
    { value: "AL", label: "AL" },
    { value: "AP", label: "AP" },
    { value: "AM", label: "AM" },
    { value: "BA", label: "BA" },
    { value: "CE", label: "CE" },
    { value: "DF", label: "DF" },
    { value: "ES", label: "ES" },
    { value: "GO", label: "GO" },
    { value: "MA", label: "MA" },
    { value: "MT", label: "MT" },
    { value: "MS", label: "MS" },
    { value: "MG", label: "MG" },
    { value: "PA", label: "PA" },
    { value: "PB", label: "PB" },
    { value: "PR", label: "PR" },
    { value: "PE", label: "PE" },
    { value: "PI", label: "PI" },
    { value: "RJ", label: "RJ" },
    { value: "RN", label: "RN" },
    { value: "RS", label: "RS" },
    { value: "RO", label: "RO" },
    { value: "RR", label: "RR" },
    { value: "SC", label: "SC" },
    { value: "SP", label: "SP" },
    { value: "SE", label: "SE" },
    { value: "TO", label: "TO" }
  ],

  paises: [
    { value: "", label: "Selecione" },
    { value: "AF", label: "Afeganistão" },
    { value: "ZA", label: "África do Sul" },
    { value: "DE", label: "Alemanha" },
    { value: "SA", label: "Arábia Saudita" },
    { value: "AR", label: "Argentina" },
    { value: "AU", label: "Austrália" },
    { value: "AT", label: "Áustria" },
    { value: "BE", label: "Bélgica" },
    { value: "BO", label: "Bolívia" },
    { value: "BR", label: "Brasil" },
    { value: "CA", label: "Canadá" },
    { value: "CL", label: "Chile" },
    { value: "CN", label: "China" },
    { value: "CO", label: "Colômbia" },
    { value: "KR", label: "Coreia do Sul" },
    { value: "CU", label: "Cuba" },
    { value: "DK", label: "Dinamarca" },
    { value: "EG", label: "Egito" },
    { value: "AE", label: "Emirados Árabes Unidos" },
    { value: "EC", label: "Equador" },
    { value: "ES", label: "Espanha" },
    { value: "US", label: "Estados Unidos" },
    { value: "FR", label: "França" },
    { value: "GR", label: "Grécia" },
    { value: "IN", label: "Índia" },
    { value: "ID", label: "Indonésia" },
    { value: "IQ", label: "Irã" },
    { value: "IT", label: "Itália" },
    { value: "JP", label: "Japão" },
    { value: "MX", label: "México" },
    { value: "NG", label: "Nigéria" },
    { value: "NL", label: "Países Baixos" },
    { value: "PK", label: "Paquistão" },
    { value: "PE", label: "Peru" },
    { value: "PT", label: "Portugal" },
    { value: "GB", label: "Reino Unido" },
    { value: "RU", label: "Rússia" },
    { value: "CH", label: "Suíça" },
    { value: "SE", label: "Suécia" },
    { value: "TH", label: "Tailândia" },
    { value: "TR", label: "Turquia" },
    { value: "UA", label: "Ucrânia" },
    { value: "UY", label: "Uruguai" },
    { value: "VE", label: "Venezuela" },
    { value: "VN", label: "Vietnã" }
  ].sort((a, b) => a.label.localeCompare(b.label))
  
};

export const combustivelOptions = [
  "DIESEL",
  "GASOLINA",
];

export const tipoOptions = [
  "AMBULANCIA",
  "CARRO",
  "CAMINHAO",
  "CAMINHONETA",
  "MOTO",
  "ONIBUS",
  "VAN",
  "TRATOR",
  "MAQUINA",
  "OUTROS",
];

export const statusVeiculo = [
  "DISPONIVEL",
  "RESERVADO",
  "EM MANUNTENCAO",
  "EM USO",
];


// Opções para o select de tipo de estabelecimento
export const tiposEstabelecimento = [
  { value: "", label: "SELECIONE UMA OPÇÃO" },
  { value: "Academia de Ginástica", label: "ACADEMIA DE GINÁSTICA" },
  { value: "Ambulatório", label: "AMBULATÓRIO" },
  { value: "Armazenagem para terceiros", label: "ARMAZENAGEM PARA TERCEIROS" },
  { value: "Albergue", label: "ALBERGUE" },
  { value: "Bar", label: "BAR" },
  { value: "Berçário", label: "BERÇÁRIO" },
  { value: "Bomboniere", label: "BOMBONIERE" },
  { value: "Barbearia", label: "BARBEARIA" },
  { value: "Comércio varejista de carne sem manipulação", label: "COMÉRCIO VAREJISTA DE CARNE SEM MANIPULAÇÃO" },
  { value: "Comércio varejista de pescado sem manipulação", label: "COMÉRCIO VAREJISTA DE PESCADO SEM MANIPULAÇÃO" },
  { value: "Creche", label: "CRECHE" },
  { value: "Clínica com Internamento", label: "CLÍNICA COM INTERNAMENTO" },
  { value: "Clínica com vacinação", label: "CLÍNICA COM VACINAÇÃO" },
  { value: "Clínica de Radiologia", label: "CLÍNICA DE RADIOLOGIA" },
  { value: "Clínica de Serviços de Imagem médica", label: "CLÍNICA DE SERVIÇOS DE IMAGEM MÉDICA" },
  { value: "Clínica de Serviços de Imagem odontológica", label: "CLÍNICA DE SERVIÇOS DE IMAGEM ODONTOLÓGICA" },
  { value: "Clínica em geral sem internamento", label: "CLÍNICA EM GERAL SEM INTERNAMENTO" },
  { value: "Clínica Odontológica", label: "CLÍNICA ODONTOLÓGICA" },
  { value: "Clínica Veterinária", label: "CLÍNICA VETERINÁRIA" },
  { value: "Consultório Veterinário", label: "CONSULTÓRIO VETERINÁRIO" },
  { value: "Comércio Veterinário", label: "COMÉRCIO VETERINÁRIO" },
  { value: "Comércio atacadista com armazenamento", label: "COMÉRCIO ATACADISTA COM ARMAZENAMENTO" },
  { value: "Comércio atacadista sem armazenamento", label: "COMÉRCIO ATACADISTA SEM ARMAZENAMENTO" },
  { value: "Comércio de produtos de higiene pessoal", label: "COMÉRCIO DE PRODUTOS DE HIGIENE PESSOAL" },
  { value: "Comércio de cosméticos", label: "COMÉRCIO DE COSMÉTICOS" },
  { value: "Comércio de perfumes", label: "COMÉRCIO DE PERFUMES" },
  { value: "Comércio de saneantes domissanitários", label: "COMÉRCIO DE SANEANTES DOMISSANITÁRIOS" },
  { value: "Comércio de produtos agro-veterinários", label: "COMÉRCIO DE PRODUTOS AGRO-VETERINÁRIOS" },
  { value: "Comércio de produtos naturais", label: "COMÉRCIO DE PRODUTOS NATURAIS" },
  { value: "Comércio varejista de materiais médicos", label: "COMÉRCIO VAREJISTA DE MATERIAIS MÉDICOS" },
  { value: "Comércio varejista de materiais odontológicos", label: "COMÉRCIO VAREJISTA DE MATERIAIS ODONTOLÓGICOS" },
  { value: "Consultório Médico", label: "CONSULTÓRIO MÉDICO" },
  { value: "Consultório Odontológico", label: "CONSULTÓRIO ODONTOLÓGICO" },
  { value: "Consultório de nutrição", label: "CONSULTÓRIO DE NUTRIÇÃO" },
  { value: "Consultório de psicologia", label: "CONSULTÓRIO DE PSICOLOGIA" },
  { value: "Consultório de terapia ocupacional", label: "CONSULTÓRIO DE TERAPIA OCUPACIONAL" },
  { value: "Consultório de fisioterapia", label: "CONSULTÓRIO DE FISIOTERAPIA" },
  { value: "Controladora de Pragas", label: "CONTROLADORA DE PRAGAS" },
  { value: "Cozinha industrial", label: "COZINHA INDUSTRIAL" },
  { value: "Casa de Cômodo", label: "CASA DE CÔMODO" },
  { value: "Comércio varejista de bebidas", label: "COMÉRCIO VAREJISTA DE BEBIDAS" },
  { value: "Cabeleireiro", label: "CABELEIREIRO" },
  { value: "Distribuidor", label: "DISTRIBUIDOR" },
  { value: "Depósito próprio de produtos alimentícios", label: "DEPÓSITO PRÓPRIO DE PRODUTOS ALIMENTÍCIOS" },
  { value: "Distribuidor sem armazenamento", label: "DISTRIBUIDOR SEM ARMAZENAMENTO" },
  { value: "Drogaria", label: "DROGARIA" },
  { value: "Empresa de prestação de serviços de saúde", label: "EMPRESA DE PRESTAÇÃO DE SERVIÇOS DE SAÚDE" },
  { value: "Empresa limpadora de caixa d'água", label: "EMPRESA LIMPADORA DE CAIXA D'ÁGUA" },
  { value: "Empresa limpadora de fossa", label: "EMPRESA LIMPADORA DE FOSSA" },
  { value: "Empresa que explora água natural potável", label: "EMPRESA QUE EXPLORA ÁGUA NATURAL POTÁVEL" },
  { value: "Empresa que explora e transporta água natural potável", label: "EMPRESA QUE EXPLORA E TRANSPORTA ÁGUA NATURAL POTÁVEL" },
  { value: "Empresa que transporta água natural potável", label: "EMPRESA QUE TRANSPORTA ÁGUA NATURAL POTÁVEL" },
  { value: "Escola", label: "ESCOLA" },
  { value: "Estúdio de Tatuagem", label: "ESTÚDIO DE TATUAGEM" },
  { value: "Estúdio de piercing", label: "ESTÚDIO DE PIERCING" },
  { value: "Fornecimento de alimentos preparados para domicílios", label: "FORNECIMENTO DE ALIMENTOS PREPARADOS PARA DOMICÍLIOS" },
  { value: "Farmácia Veterinária", label: "FARMÁCIA VETERINÁRIA" },
  { value: "Fábrica de gelo", label: "FÁBRICA DE GELO" },
  { value: "Farmácia", label: "FARMÁCIA" },
  { value: "Hortifrutigranjeiro", label: "HORTIFRUTIGRANJEIRO" },
  { value: "Hotelzinho", label: "HOTELZINHO" },
  { value: "Hotel com restaurante", label: "HOTEL COM RESTAURANTE" },
  { value: "Hotel", label: "HOTEL" },
  { value: "Hospedaria", label: "HOSPEDARIA" },
  { value: "Hipermercado", label: "HIPERMERCADO" },
  { value: "Instituição Assistencial", label: "INSTITUIÇÃO ASSISTENCIAL" },
  { value: "Instituição de Longa Permanência para Idosos", label: "INSTITUIÇÃO DE LONGA PERMANÊNCIA PARA IDOSOS (ILPI)" },
  { value: "Lanchonete", label: "LANCHONETE" },
  { value: "Laboratório de análise de água", label: "LABORATÓRIO DE ANÁLISE DE ÁGUA" },
  { value: "Laboratório de prótese dentária", label: "LABORATÓRIO DE PRÓTESE DENTÁRIA" },
  { value: "Laboratório de análises clínicas", label: "LABORATÓRIO DE ANÁLISES CLÍNICAS" },
  { value: "Loja de Conveniência", label: "LOJA DE CONVENIÊNCIA" },
  { value: "Minimercado", label: "MINIMERCADO" },
  { value: "Massagem", label: "MASSAGEM" },
  { value: "Mercearia", label: "MERCEARIA" },
  { value: "Motel", label: "MOTEL" },
  { value: "Ótica", label: "ÓTICA" },
  { value: "Padaria sem preparo de refeições", label: "PADARIA SEM PREPARO DE REFEIÇÕES" },
  { value: "Pet-shop", label: "PET-SHOP" },
  { value: "Padaria com delicatessen", label: "PADARIA COM DELICATESSEN" },
  { value: "Pensão", label: "PENSÃO" },
  { value: "Pousada", label: "POUSADA" },
  { value: "Podologia", label: "PODOLOGIA" },
  { value: "Posto de coleta laboratorial", label: "POSTO DE COLETA LABORATORIAL" },
  { value: "Refeitório", label: "REFEITÓRIO" },
  { value: "Sauna", label: "SAUNA" },
  { value: "Sorveteria", label: "SORVETERIA" },
  { value: "Serviço de buffet", label: "SERVIÇO DE BUFFET" },
  { value: "Salão de beleza", label: "SALÃO DE BELEZA" },
  { value: "Serviço de estética", label: "SERVIÇO DE ESTÉTICA" },
  { value: "Serviço de massagem", label: "SERVIÇO DE MASSAGEM" },
  { value: "Serviço de podologia", label: "SERVIÇO DE PODOLOGIA" },
  { value: "Serviço de cuidados de beleza", label: "SERVIÇO DE CUIDADOS DE BELEZA" },
  { value: "Serviço de Lavanderia", label: "SERVIÇO DE LAVANDERIA" },
  { value: "Serviço Funerário", label: "SERVIÇO FUNERÁRIO" },
  { value: "Supermercado", label: "SUPERMERCADO" },
  { value: "Transportadora", label: "TRANSPORTADORA" },
];


  
  